apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bandcheck-backend
  namespace: bandcheck
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: bandcheck-add-api-prefix@kubernetescrd
    external-dns.alpha.kubernetes.io/hostname: bandcheck-api.marcodoes.tech
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - bandcheck-api.marcodoes.tech
    secretName: bandcheck-backend-tls
  rules:
  - host: bandcheck-api.marcodoes.tech
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bandcheck-backend
            port:
              number: 80
