apiVersion: v1
kind: Service
metadata:
  name: bandcheck-backend
  namespace: bandcheck
  labels:
    app: bandcheck-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: bandcheck-backend
