apiVersion: v1
kind: Service
metadata:
  name: bandcheck-frontend
  namespace: bandcheck
  labels:
    app: bandcheck-frontend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: bandcheck-frontend
